Signature       DB 00Bh, 0ADh, 05Eh, 0EDh                       ; LOCKIT signature
		DB 2, 3						; Version (maj, min)
                DB 10                                           ; Sixe: 10 bytes
ExitMode        DB 000h                                         ; Normal exit

AWARD           DB 0E9h, 065h                                   ; Password:
AMI             DB 0F0h, 03Dh, 0A8h, 0E6h, 078h, 0A3h, 090h     ; "unlock"
